apiVersion: v1
kind: ConfigMap
metadata:
  name: rocketmq-configmap
data:
  rocketmq.yaml: |
    name: RocketMQ
    driverClass: io.openchaos.driver.rocketmq.RocketMQDriver
    
    endToEndLatencyCheck: true
    
    # RocketMQ cluster configuration
    
    # Nodes for broker
    nodes: 
    - rocketmq-broker-0-ssh
    - rocketmq-broker-1-ssh
    
    # Nodes for nameserver
    metaNodes:
    - nameserver-ssh
    
    # RocketMQ configuration
    rocketmqVersion: 5.2.0
    installDir: /home/rocketmq/rocketmq-5.2.0 # you could set existent location for RocketMQ
    nameServerPort: 9876
    
    # RocketMQ client configuration
    clusterName: DefaultCluster # same value as the config in broker.properties
    vipChannelEnabled: false
    
    # RocketMQ broker configuration
    brokerClusterName: DefaultCluster
    brokerName: rocketmq-broker-0
    storePathRootDir: /home/rocketmq/store
    storePathCommitLog: /home/rocketmq/store/commitlog
    enableDLegerCommitLog: false

