name: TEST_ROCKETMQ_TEST_TOOL

on: [push]

env:
  ACTION: deploy
  VERSION: Wuyunfan-BUPT-patch-13-1bcdbc6f-810c-483f-8cc8-ec7767d62ad5-ubuntu
  ASK_CONFIG: abcdefghijklmnopqlstuvwxyz
  DOCKER_REPO_USERNAME: ${{ secrets.DOCKERHUB_USER }}
  DOCKER_REPO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  CHART_GIT: https://ghproxy.com/https://github.com/apache/rocketmq-docker.git
  CHART_BRANCH: master
  CHART_PATH: ./rocketmq-k8s-helm
  TEST_CODE_GIT: https://ghproxy.com/https://github.com/apache/rocketmq-e2e.git
  TEST_CODE_BRANCH: master
  TEST_CODE_PATH: java/e2e
  TEST_CMD_BASE: mvn -B test
  JOB_INDEX: 1

jobs:
  print-values:
    name: print all values
    runs-on: ubuntu-latest
    timeout-minutes:
    steps:
      - name: print current diectory
        run: ls ./
      - name: print GITHUB_REPOSITORY
        run: echo "${GITHUB_REPOSITORY#*/} | sed -e "s/\//-/g" | cut -c1-36 | tr '[A-Z]' '[a-z]'"
      - name: print GITHUB_WORKFLOW
        run: echo "${GITHUB_WORKFLOW}"
      - name: print GITHUB_RUN_ID
        run: echo "${GITHUB_RUN_ID}"
      - name: print home
        run: echo "${HOME}"
      - name: execute scripts
        run: ./entry1.sh
      
      
